graph TB
A[Markdown] --> BA[Documents]
A --> BB[Presentations]
BA --> B[Notebook]
BA --> C[HTML]
BA --> D[PDF]
BA --> E[Word]
BA --> F[ODT]
BA --> G[RTF]
BA --> H[Markdown]
BB --> I[ioslides]
BB --> J[reveal.js]
BB --> K[Slidy]
BB --> L[Beamer]
BB --> M[PowerPoint]
